### ISSUE TITLE
Unable to build on VS2013 Community Edition

### ISSUE THREAD

**Issue by ghost** [aycwabtu/aycwabtu#1]
Error   70  error LNK2005: _aycw_block_decrypt already defined in aycwabtu_bs_block_ab.obj  
Error   71  error LNK2005: _aycw_block_key_schedule already defined in aycwabtu_bs_block_ab.obj 
Error   72  error LNK2005: _aycw_checkPESheader already defined in aycwabtu_bs_block_ab.obj 
Error   73  error LNK2005: _aycw_init_block already defined in aycwabtu_bs_block_ab.obj 
Error   74  error LNK1169: one or more multiply defined symbols found

**Comment by aycwabtu** [comment]
Fixed in [eb8fb6](https://github.com/aycwabtu/aycwabtu/commit/eb8fb674c7d4e104a03b03b8d0ae0004dc68d52c). Thanks for the hint.
